name: Test chpass
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run Unit Tests
        run: pipenv run unit_tests
